// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlLesson = "al_lesson"

// AlLesson mapped from table <al_lesson>
type AlLesson struct {
	ID          string `gorm:"column:id;primaryKey" json:"id"`
	TopicID     string `gorm:"column:topic_id" json:"topic_id"`
	Title       string `gorm:"column:title;not null" json:"title"`
	Objectives  string `gorm:"column:objectives" json:"objectives"`
	Content     string `gorm:"column:content" json:"content"`
	OrderNumber int32  `gorm:"column:order_number;not null" json:"order_number"`
}

// TableName AlLesson's table name
func (*AlLesson) TableName() string {
	return TableNameAlLesson
}
