// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	"github.com/lib/pq"
)

const TableNameAlLesson = "al_lesson"

// AlLesson mapped from table <al_lesson>
type AlLesson struct {
	ID          uuid.UUID `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	TopicID     uuid.UUID `gorm:"column:topic_id" json:"topic_id"`
	Title       string `gorm:"column:title;not null" json:"title"`
	Objectives  pq.StringArray `gorm:"column:objectives;type:text[]" json:"objectives"`
	Content     pq.StringArray `gorm:"column:content;type:text[]" json:"content"`
	OrderNumber int32  `gorm:"column:order_number;not null" json:"order_number"`
}

// TableName AlLesson's table name
func (*AlLesson) TableName() string {
	return TableNameAlLesson
}
