// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlQuestion = "al_question"

// AlQuestion mapped from table <al_question>
type AlQuestion struct {
	ID            string `gorm:"column:id;primaryKey" json:"id"`
	LessonID      string `gorm:"column:lesson_id" json:"lesson_id"`
	QuestionText  string `gorm:"column:question_text" json:"question_text"`
	OrderNumber   int32  `gorm:"column:order_number;not null" json:"order_number"`
	Options       string `gorm:"column:options;not null" json:"options"`
	CorrectAnswer int32  `gorm:"column:correct_answer;not null" json:"correct_answer"`
}

// TableName AlQuestion's table name
func (*AlQuestion) TableName() string {
	return TableNameAlQuestion
}
