// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlRefreshToken = "al_refresh_token"

// AlRefreshToken mapped from table <al_refresh_token>
type AlRefreshToken struct {
	RefreshToken   string    `gorm:"column:refresh_token;primaryKey" json:"refresh_token"`
	UserID         string    `gorm:"column:user_id" json:"user_id"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	LastAccessedAt time.Time `gorm:"column:last_accessed_at" json:"last_accessed_at"`
}

// TableName AlRefreshToken's table name
func (*AlRefreshToken) TableName() string {
	return TableNameAlRefreshToken
}
