// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlStatus = "al_status"

// AlStatus mapped from table <al_status>
type AlStatus struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name" json:"name"`
}

// TableName AlStatus's table name
func (*AlStatus) TableName() string {
	return TableNameAlStatus
}
