// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlTopic = "al_topic"

// AlTopic mapped from table <al_topic>
type AlTopic struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	Title     string    `gorm:"column:title;not null" json:"title"`
	IsPublic  bool      `gorm:"column:is_public;not null" json:"is_public"`
	Emoji     string    `gorm:"column:emoji;not null" json:"emoji"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	CreatedBy string    `gorm:"column:created_by" json:"created_by"`
	StatusID  int32     `gorm:"column:status_id" json:"status_id"`
}

// TableName AlTopic's table name
func (*AlTopic) TableName() string {
	return TableNameAlTopic
}
