// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlUser = "al_user"

// AlUser mapped from table <al_user>
type AlUser struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Username    string    `gorm:"column:username" json:"username"`
	Fullname    string    `gorm:"column:fullname" json:"fullname"`
	GoogleSubID string    `gorm:"column:google_sub_id;not null" json:"google_sub_id"`
	PictureURL  string    `gorm:"column:picture_url" json:"picture_url"`
	Email       string    `gorm:"column:email;not null" json:"email"`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	Status      int32     `gorm:"column:status" json:"status"`
}

// TableName AlUser's table name
func (*AlUser) TableName() string {
	return TableNameAlUser
}
