// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/google/uuid"

const TableNameAlUserTopicProgress = "al_user_topic_progress"

// AlUserTopicProgress mapped from table <al_user_topic_progress>
type AlUserTopicProgress struct {
	ID            uuid.UUID `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	TopicID       uuid.UUID `gorm:"column:topic_id" json:"topic_id"`
	UserID        uuid.UUID `gorm:"column:user_id" json:"user_id"`
	CurrentLesson int32  `gorm:"column:current_lesson" json:"current_lesson"`
}

// TableName AlUserTopicProgress's table name
func (*AlUserTopicProgress) TableName() string {
	return TableNameAlUserTopicProgress
}
